#! /bin/sh

rsync -avL --timeout 10 --delete --exclude '*.inc*' --exclude '*.lib*' --exclude '*.build*' --exclude '*.orig' --exclude 'deploy*' --exclude scratch . alex@alex.condensation.io:/srv/alex.condensation.io/http
