#! /bin/sh

rsync -avL --timeout 10 --delete --exclude '*.inc*' --exclude '*.lib*' --exclude '*.build*' --exclude '*.orig' --exclude 'deploy*' --exclude scratch . thomas@condensation.io:/srv/data/Condensation/http
