#! /bin/sh

rsync -avL --timeout 10 --delete --exclude '*.inc*' --exclude '*.lib*' --exclude '*.build*' --exclude '*.orig' --exclude 'deploy*' --exclude scratch . thomas@thomas.condensation.io:/srv/thomas.condensation.io/http
